# Generated by Django 2.2.10 on 2020-12-18 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Last_login',
            fields=[
                ('user', models.CharField(default='1', max_length=50, primary_key=True, serialize=False)),
                ('last_login', models.DateField(default=datetime.date(2020, 12, 18))),
            ],
        ),
    ]
