# Generated by Django 2.2.10 on 2020-12-21 08:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_last_login_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='last_login',
            name='last_login',
            field=models.DateField(default=datetime.date(2020, 12, 21)),
        ),
    ]
